sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js:
  - '10'
  - '12'
  - '13'
install: npm install
script: npm run validate
after_success: node src travis-after-success
branches:
  only:
    - master
