module.exports = {
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  arrowParens: 'avoid',
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'css',
  insertPragma: false,
  jsxSingleQuote: false,
  quoteProps: 'as-needed',
  requirePragma: false,
  singleQuote: true,
  trailingComma: 'all',
  jsxBracketSameLine: false,
  proseWrap: 'always',
  vueIndentScriptAndStyle: false,
};
